version: "3"
services:
  valheim:
    image: lloesche/valheim-server:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      - SERVER_PORT=2456
      - SERVER_NAME="Created With Valheim Docker"
      - WORLD_NAME="Dedicated"
      - SERVER_PASS="poggers"
      - SERVER_PUBLIC=0
    volumes:
    - $HOME/valheim-server-config:/config \